CREATE SEQUENCE CP_CLIENT_GEN_SEQ As integer START WITH 1 INCREMENT BY 1
    MINVALUE 1 MAXVALUE 10000 NO CYCLE;

CREATE SEQUENCE CP_ACCOUNT_GEN_SEQ As integer START WITH 1 INCREMENT BY 1
    MINVALUE 1 MAXVALUE 10000 NO CYCLE;

CREATE SEQUENCE CP_MOVEMENT_GEN_SEQ As integer START WITH 1 INCREMENT BY 1
    MINVALUE 1 MAXVALUE 10000 NO CYCLE;